# Generated by Django 3.0.6 on 2020-05-20 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pediatrician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('genre', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
            ],
            options={
                'verbose_name': 'Pediatra',
                'verbose_name_plural': 'Pediatras',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentScheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time_start', models.DateTimeField()),
                ('time_finish', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('pediatrician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pediatrician')),
            ],
            options={
                'verbose_name': 'Programación de cita',
                'verbose_name_plural': 'Programación de citas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
                ('appointment_scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AppointmentScheduling')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-created'],
            },
        ),
    ]
